spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_library
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jmx:
    enabled: true
  data:
    rest:
      basePath: /dataRest
logging:
  level:
    ROOT: INFO
  file:
    name: application.log
management:
  endpoints:
    web:
      exposure:
        include: metrics, health, logfile
  endpoint:
    health:
      show-details: always
