spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_library
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
#      data-locations: data.sql
#      schema-locations: schema.sql
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#logging:
#  level:
#    ROOT: ERROR
