spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_library
    username: postgre
    password: postgre
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

    show-sql: true